/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "azdnuhjpjzxmxnfcvpkm";
export const publicAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6ZG51aGpwanp4bXhuZmN2cGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MDMzNDAsImV4cCI6MjA3ODE3OTM0MH0.P0YLG-h04ul3V9OHvvjr-vrmChcxSczkzSJF6wvdhTg";